// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.3
//   protoc               v5.28.2
// source: hero/hero.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";

export const protobufPackage = "hero";

export interface FindOneHeroConditions {
  readonly id?: number | null | undefined;
  readonly type?: string | null | undefined;
}

export interface Hero {
  readonly id: number;
  readonly name: string;
  readonly type: string;
}

function createBaseFindOneHeroConditions(): FindOneHeroConditions {
  return { id: null, type: null };
}

export const FindOneHeroConditions: MessageFns<FindOneHeroConditions> = {
  encode(
    message: FindOneHeroConditions,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.id !== undefined && message.id !== null) {
      writer.uint32(8).int32(message.id);
    }
    if (message.type !== undefined && message.type !== null) {
      writer.uint32(18).string(message.type);
    }
    return writer;
  },

  decode(
    input: BinaryReader | Uint8Array,
    length?: number,
  ): FindOneHeroConditions {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFindOneHeroConditions() as any;
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.type = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FindOneHeroConditions {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : null,
      type: isSet(object.type) ? globalThis.String(object.type) : null,
    };
  },

  toJSON(message: FindOneHeroConditions): unknown {
    const obj: any = {};
    if (message.id !== undefined && message.id !== null) {
      obj.id = Math.round(message.id);
    }
    if (message.type !== undefined && message.type !== null) {
      obj.type = message.type;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<FindOneHeroConditions>, I>>(
    base?: I,
  ): FindOneHeroConditions {
    return FindOneHeroConditions.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FindOneHeroConditions>, I>>(
    object: I,
  ): FindOneHeroConditions {
    const message = createBaseFindOneHeroConditions() as any;
    message.id = object.id ?? undefined;
    message.type = object.type ?? undefined;
    return message;
  },
};

function createBaseHero(): Hero {
  return { id: 0, name: "", type: "" };
}

export const Hero: MessageFns<Hero> = {
  encode(
    message: Hero,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int32(message.id);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.type !== "") {
      writer.uint32(26).string(message.type);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Hero {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHero() as any;
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.type = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Hero {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      type: isSet(object.type) ? globalThis.String(object.type) : "",
    };
  },

  toJSON(message: Hero): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.type !== "") {
      obj.type = message.type;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Hero>, I>>(base?: I): Hero {
    return Hero.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Hero>, I>>(object: I): Hero {
    const message = createBaseHero() as any;
    message.id = object.id ?? 0;
    message.name = object.name ?? "";
    message.type = object.type ?? "";
    return message;
  },
};

export type HeroServiceService = typeof HeroServiceService;
export const HeroServiceService = {
  findOne: {
    path: "/hero.HeroService/FindOne",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: FindOneHeroConditions) => Buffer.from(FindOneHeroConditions.encode(value).finish()),
    requestDeserialize: (value: Buffer) => FindOneHeroConditions.decode(value),
    responseSerialize: (value: Hero) => Buffer.from(Hero.encode(value).finish()),
    responseDeserialize: (value: Buffer) => Hero.decode(value),
  },
} as const;

export interface HeroServiceServer extends UntypedServiceImplementation {
  findOne: handleUnaryCall<FindOneHeroConditions, Hero>;
}

export interface HeroServiceClient extends Client {
  findOne(
    request: FindOneHeroConditions,
    callback: (error: ServiceError | null, response: Hero) => void,
  ): ClientUnaryCall;
  findOne(
    request: FindOneHeroConditions,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: Hero) => void,
  ): ClientUnaryCall;
  findOne(
    request: FindOneHeroConditions,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: Hero) => void,
  ): ClientUnaryCall;
}

export const HeroServiceClient = makeGenericClientConstructor(
  HeroServiceService,
  "hero.HeroService",
) as unknown as {
  new (
    address: string,
    credentials: ChannelCredentials,
    options?: Partial<ClientOptions>,
  ): HeroServiceClient;
  service: typeof HeroServiceService;
  serviceName: string;
};

export interface DataLoaderOptions {
  cache?: boolean;
}

export interface DataLoaders {
  rpcDataLoaderOptions?: DataLoaderOptions;
  getDataLoader<T>(identifier: string, constructorFn: () => T): T;
}

type Builtin =
  | Date
  | Function
  | Uint8Array
  | string
  | number
  | boolean
  | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  :
    & P
    & { [K in keyof P]: Exact<P[K], I[K]> }
    & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
