// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.2
// source: vehicle/vehicle.proto

package vehicle

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VehicleType int32

const (
	VehicleType_UNSPECIFIED VehicleType = 0
	VehicleType_SUV         VehicleType = 1
	VehicleType_MINIVAN     VehicleType = 2
	VehicleType_COUPE       VehicleType = 3
	VehicleType_SEDAN       VehicleType = 4
	VehicleType_PICKUP      VehicleType = 5
	VehicleType_TRUNK       VehicleType = 6
	VehicleType_VAN         VehicleType = 7
	VehicleType_LIMOUSINE   VehicleType = 8
)

// Enum value maps for VehicleType.
var (
	VehicleType_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "SUV",
		2: "MINIVAN",
		3: "COUPE",
		4: "SEDAN",
		5: "PICKUP",
		6: "TRUNK",
		7: "VAN",
		8: "LIMOUSINE",
	}
	VehicleType_value = map[string]int32{
		"UNSPECIFIED": 0,
		"SUV":         1,
		"MINIVAN":     2,
		"COUPE":       3,
		"SEDAN":       4,
		"PICKUP":      5,
		"TRUNK":       6,
		"VAN":         7,
		"LIMOUSINE":   8,
	}
)

func (x VehicleType) Enum() *VehicleType {
	p := new(VehicleType)
	*p = x
	return p
}

func (x VehicleType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VehicleType) Descriptor() protoreflect.EnumDescriptor {
	return file_vehicle_vehicle_proto_enumTypes[0].Descriptor()
}

func (VehicleType) Type() protoreflect.EnumType {
	return &file_vehicle_vehicle_proto_enumTypes[0]
}

func (x VehicleType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VehicleType.Descriptor instead.
func (VehicleType) EnumDescriptor() ([]byte, []int) {
	return file_vehicle_vehicle_proto_rawDescGZIP(), []int{0}
}

type FindVehicleConditions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Brand string `protobuf:"bytes,1,opt,name=brand,proto3" json:"brand,omitempty"`
}

func (x *FindVehicleConditions) Reset() {
	*x = FindVehicleConditions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vehicle_vehicle_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindVehicleConditions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindVehicleConditions) ProtoMessage() {}

func (x *FindVehicleConditions) ProtoReflect() protoreflect.Message {
	mi := &file_vehicle_vehicle_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindVehicleConditions.ProtoReflect.Descriptor instead.
func (*FindVehicleConditions) Descriptor() ([]byte, []int) {
	return file_vehicle_vehicle_proto_rawDescGZIP(), []int{0}
}

func (x *FindVehicleConditions) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

type FindOneVehicleConditions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *FindOneVehicleConditions) Reset() {
	*x = FindOneVehicleConditions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vehicle_vehicle_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindOneVehicleConditions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindOneVehicleConditions) ProtoMessage() {}

func (x *FindOneVehicleConditions) ProtoReflect() protoreflect.Message {
	mi := &file_vehicle_vehicle_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindOneVehicleConditions.ProtoReflect.Descriptor instead.
func (*FindOneVehicleConditions) Descriptor() ([]byte, []int) {
	return file_vehicle_vehicle_proto_rawDescGZIP(), []int{1}
}

func (x *FindOneVehicleConditions) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Vehicles struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vehicles []*Vehicle `protobuf:"bytes,1,rep,name=vehicles,proto3" json:"vehicles,omitempty"`
}

func (x *Vehicles) Reset() {
	*x = Vehicles{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vehicle_vehicle_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Vehicles) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vehicles) ProtoMessage() {}

func (x *Vehicles) ProtoReflect() protoreflect.Message {
	mi := &file_vehicle_vehicle_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vehicles.ProtoReflect.Descriptor instead.
func (*Vehicles) Descriptor() ([]byte, []int) {
	return file_vehicle_vehicle_proto_rawDescGZIP(), []int{2}
}

func (x *Vehicles) GetVehicles() []*Vehicle {
	if x != nil {
		return x.Vehicles
	}
	return nil
}

type Vehicle struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int32       `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name  string      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Brand string      `protobuf:"bytes,3,opt,name=brand,proto3" json:"brand,omitempty"`
	Type  VehicleType `protobuf:"varint,4,opt,name=type,proto3,enum=vehicle.VehicleType" json:"type,omitempty"`
}

func (x *Vehicle) Reset() {
	*x = Vehicle{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vehicle_vehicle_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Vehicle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vehicle) ProtoMessage() {}

func (x *Vehicle) ProtoReflect() protoreflect.Message {
	mi := &file_vehicle_vehicle_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vehicle.ProtoReflect.Descriptor instead.
func (*Vehicle) Descriptor() ([]byte, []int) {
	return file_vehicle_vehicle_proto_rawDescGZIP(), []int{3}
}

func (x *Vehicle) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Vehicle) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Vehicle) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *Vehicle) GetType() VehicleType {
	if x != nil {
		return x.Type
	}
	return VehicleType_UNSPECIFIED
}

var File_vehicle_vehicle_proto protoreflect.FileDescriptor

var file_vehicle_vehicle_proto_rawDesc = []byte{
	0x0a, 0x15, 0x76, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x2f, 0x76, 0x65, 0x68, 0x69, 0x63, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x76, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65,
	0x22, 0x2d, 0x0a, 0x15, 0x46, 0x69, 0x6e, 0x64, 0x56, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x43,
	0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x72, 0x61,
	0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x62, 0x72, 0x61, 0x6e, 0x64, 0x22,
	0x2a, 0x0a, 0x18, 0x46, 0x69, 0x6e, 0x64, 0x4f, 0x6e, 0x65, 0x56, 0x65, 0x68, 0x69, 0x63, 0x6c,
	0x65, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x38, 0x0a, 0x08, 0x56,
	0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x73, 0x12, 0x2c, 0x0a, 0x08, 0x76, 0x65, 0x68, 0x69, 0x63,
	0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x76, 0x65, 0x68, 0x69,
	0x63, 0x6c, 0x65, 0x2e, 0x56, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x52, 0x08, 0x76, 0x65, 0x68,
	0x69, 0x63, 0x6c, 0x65, 0x73, 0x22, 0x6d, 0x0a, 0x07, 0x56, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x72, 0x61, 0x6e, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x62, 0x72, 0x61, 0x6e, 0x64, 0x12, 0x28, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x76, 0x65, 0x68, 0x69, 0x63,
	0x6c, 0x65, 0x2e, 0x56, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x2a, 0x79, 0x0a, 0x0b, 0x56, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x0f, 0x0a, 0x0b, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49,
	0x45, 0x44, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x53, 0x55, 0x56, 0x10, 0x01, 0x12, 0x0b, 0x0a,
	0x07, 0x4d, 0x49, 0x4e, 0x49, 0x56, 0x41, 0x4e, 0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x43, 0x4f,
	0x55, 0x50, 0x45, 0x10, 0x03, 0x12, 0x09, 0x0a, 0x05, 0x53, 0x45, 0x44, 0x41, 0x4e, 0x10, 0x04,
	0x12, 0x0a, 0x0a, 0x06, 0x50, 0x49, 0x43, 0x4b, 0x55, 0x50, 0x10, 0x05, 0x12, 0x09, 0x0a, 0x05,
	0x54, 0x52, 0x55, 0x4e, 0x4b, 0x10, 0x06, 0x12, 0x07, 0x0a, 0x03, 0x56, 0x41, 0x4e, 0x10, 0x07,
	0x12, 0x0d, 0x0a, 0x09, 0x4c, 0x49, 0x4d, 0x4f, 0x55, 0x53, 0x49, 0x4e, 0x45, 0x10, 0x08, 0x32,
	0x8f, 0x01, 0x0a, 0x0e, 0x56, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x40, 0x0a, 0x07, 0x46, 0x69, 0x6e, 0x64, 0x4f, 0x6e, 0x65, 0x12, 0x21, 0x2e,
	0x76, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x4f, 0x6e, 0x65, 0x56,
	0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x1a, 0x10, 0x2e, 0x76, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x2e, 0x56, 0x65, 0x68, 0x69, 0x63,
	0x6c, 0x65, 0x22, 0x00, 0x12, 0x3b, 0x0a, 0x04, 0x46, 0x69, 0x6e, 0x64, 0x12, 0x1e, 0x2e, 0x76,
	0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x56, 0x65, 0x68, 0x69, 0x63,
	0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x1a, 0x11, 0x2e, 0x76,
	0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x2e, 0x56, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x73, 0x22,
	0x00, 0x42, 0x2b, 0x5a, 0x29, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x65, 0x73, 0x65, 0x72, 0x2f, 0x61, 0x63, 0x69, 0x6b, 0x2e, 0x69, 0x6f, 0x2f, 0x70, 0x6b, 0x67,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_vehicle_vehicle_proto_rawDescOnce sync.Once
	file_vehicle_vehicle_proto_rawDescData = file_vehicle_vehicle_proto_rawDesc
)

func file_vehicle_vehicle_proto_rawDescGZIP() []byte {
	file_vehicle_vehicle_proto_rawDescOnce.Do(func() {
		file_vehicle_vehicle_proto_rawDescData = protoimpl.X.CompressGZIP(file_vehicle_vehicle_proto_rawDescData)
	})
	return file_vehicle_vehicle_proto_rawDescData
}

var file_vehicle_vehicle_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_vehicle_vehicle_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_vehicle_vehicle_proto_goTypes = []any{
	(VehicleType)(0),                 // 0: vehicle.VehicleType
	(*FindVehicleConditions)(nil),    // 1: vehicle.FindVehicleConditions
	(*FindOneVehicleConditions)(nil), // 2: vehicle.FindOneVehicleConditions
	(*Vehicles)(nil),                 // 3: vehicle.Vehicles
	(*Vehicle)(nil),                  // 4: vehicle.Vehicle
}
var file_vehicle_vehicle_proto_depIdxs = []int32{
	4, // 0: vehicle.Vehicles.vehicles:type_name -> vehicle.Vehicle
	0, // 1: vehicle.Vehicle.type:type_name -> vehicle.VehicleType
	2, // 2: vehicle.VehicleService.FindOne:input_type -> vehicle.FindOneVehicleConditions
	1, // 3: vehicle.VehicleService.Find:input_type -> vehicle.FindVehicleConditions
	4, // 4: vehicle.VehicleService.FindOne:output_type -> vehicle.Vehicle
	3, // 5: vehicle.VehicleService.Find:output_type -> vehicle.Vehicles
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_vehicle_vehicle_proto_init() }
func file_vehicle_vehicle_proto_init() {
	if File_vehicle_vehicle_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_vehicle_vehicle_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*FindVehicleConditions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vehicle_vehicle_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*FindOneVehicleConditions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vehicle_vehicle_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*Vehicles); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vehicle_vehicle_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*Vehicle); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_vehicle_vehicle_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vehicle_vehicle_proto_goTypes,
		DependencyIndexes: file_vehicle_vehicle_proto_depIdxs,
		EnumInfos:         file_vehicle_vehicle_proto_enumTypes,
		MessageInfos:      file_vehicle_vehicle_proto_msgTypes,
	}.Build()
	File_vehicle_vehicle_proto = out.File
	file_vehicle_vehicle_proto_rawDesc = nil
	file_vehicle_vehicle_proto_goTypes = nil
	file_vehicle_vehicle_proto_depIdxs = nil
}
