// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.3
//   protoc               v5.28.2
// source: vehicle/vehicle.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";

export const protobufPackage = "vehicle";

export enum VehicleType {
  UNSPECIFIED = 0,
  SUV = 1,
  MINIVAN = 2,
  COUPE = 3,
  SEDAN = 4,
  PICKUP = 5,
  TRUNK = 6,
  VAN = 7,
  LIMOUSINE = 8,
  UNRECOGNIZED = -1,
}

export function vehicleTypeFromJSON(object: any): VehicleType {
  switch (object) {
    case 0:
    case "UNSPECIFIED":
      return VehicleType.UNSPECIFIED;
    case 1:
    case "SUV":
      return VehicleType.SUV;
    case 2:
    case "MINIVAN":
      return VehicleType.MINIVAN;
    case 3:
    case "COUPE":
      return VehicleType.COUPE;
    case 4:
    case "SEDAN":
      return VehicleType.SEDAN;
    case 5:
    case "PICKUP":
      return VehicleType.PICKUP;
    case 6:
    case "TRUNK":
      return VehicleType.TRUNK;
    case 7:
    case "VAN":
      return VehicleType.VAN;
    case 8:
    case "LIMOUSINE":
      return VehicleType.LIMOUSINE;
    case -1:
    case "UNRECOGNIZED":
    default:
      return VehicleType.UNRECOGNIZED;
  }
}

export function vehicleTypeToJSON(object: VehicleType): string {
  switch (object) {
    case VehicleType.UNSPECIFIED:
      return "UNSPECIFIED";
    case VehicleType.SUV:
      return "SUV";
    case VehicleType.MINIVAN:
      return "MINIVAN";
    case VehicleType.COUPE:
      return "COUPE";
    case VehicleType.SEDAN:
      return "SEDAN";
    case VehicleType.PICKUP:
      return "PICKUP";
    case VehicleType.TRUNK:
      return "TRUNK";
    case VehicleType.VAN:
      return "VAN";
    case VehicleType.LIMOUSINE:
      return "LIMOUSINE";
    case VehicleType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface FindVehicleConditions {
  readonly brand: string;
}

export interface FindOneVehicleConditions {
  readonly id: number;
}

export interface Vehicles {
  readonly vehicles: readonly Vehicle[];
}

export interface Vehicle {
  readonly id: number;
  readonly name: string;
  readonly brand: string;
  readonly type: VehicleType;
}

function createBaseFindVehicleConditions(): FindVehicleConditions {
  return { brand: "" };
}

export const FindVehicleConditions: MessageFns<FindVehicleConditions> = {
  encode(
    message: FindVehicleConditions,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.brand !== "") {
      writer.uint32(10).string(message.brand);
    }
    return writer;
  },

  decode(
    input: BinaryReader | Uint8Array,
    length?: number,
  ): FindVehicleConditions {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFindVehicleConditions() as any;
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.brand = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FindVehicleConditions {
    return {
      brand: isSet(object.brand) ? globalThis.String(object.brand) : "",
    };
  },

  toJSON(message: FindVehicleConditions): unknown {
    const obj: any = {};
    if (message.brand !== "") {
      obj.brand = message.brand;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<FindVehicleConditions>, I>>(
    base?: I,
  ): FindVehicleConditions {
    return FindVehicleConditions.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FindVehicleConditions>, I>>(
    object: I,
  ): FindVehicleConditions {
    const message = createBaseFindVehicleConditions() as any;
    message.brand = object.brand ?? "";
    return message;
  },
};

function createBaseFindOneVehicleConditions(): FindOneVehicleConditions {
  return { id: 0 };
}

export const FindOneVehicleConditions: MessageFns<FindOneVehicleConditions> = {
  encode(
    message: FindOneVehicleConditions,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int32(message.id);
    }
    return writer;
  },

  decode(
    input: BinaryReader | Uint8Array,
    length?: number,
  ): FindOneVehicleConditions {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFindOneVehicleConditions() as any;
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FindOneVehicleConditions {
    return { id: isSet(object.id) ? globalThis.Number(object.id) : 0 };
  },

  toJSON(message: FindOneVehicleConditions): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<FindOneVehicleConditions>, I>>(
    base?: I,
  ): FindOneVehicleConditions {
    return FindOneVehicleConditions.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FindOneVehicleConditions>, I>>(
    object: I,
  ): FindOneVehicleConditions {
    const message = createBaseFindOneVehicleConditions() as any;
    message.id = object.id ?? 0;
    return message;
  },
};

function createBaseVehicles(): Vehicles {
  return { vehicles: [] };
}

export const Vehicles: MessageFns<Vehicles> = {
  encode(
    message: Vehicles,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    for (const v of message.vehicles) {
      Vehicle.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Vehicles {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVehicles() as any;
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.vehicles.push(Vehicle.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Vehicles {
    return {
      vehicles: globalThis.Array.isArray(object?.vehicles) ? object.vehicles.map((e: any) => Vehicle.fromJSON(e)) : [],
    };
  },

  toJSON(message: Vehicles): unknown {
    const obj: any = {};
    if (message.vehicles?.length) {
      obj.vehicles = message.vehicles.map((e) => Vehicle.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Vehicles>, I>>(base?: I): Vehicles {
    return Vehicles.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Vehicles>, I>>(object: I): Vehicles {
    const message = createBaseVehicles() as any;
    message.vehicles = object.vehicles?.map((e) => Vehicle.fromPartial(e)) ||
      [];
    return message;
  },
};

function createBaseVehicle(): Vehicle {
  return { id: 0, name: "", brand: "", type: 0 };
}

export const Vehicle: MessageFns<Vehicle> = {
  encode(
    message: Vehicle,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int32(message.id);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.brand !== "") {
      writer.uint32(26).string(message.brand);
    }
    if (message.type !== 0) {
      writer.uint32(32).int32(message.type);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Vehicle {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVehicle() as any;
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.brand = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.type = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Vehicle {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      brand: isSet(object.brand) ? globalThis.String(object.brand) : "",
      type: isSet(object.type) ? vehicleTypeFromJSON(object.type) : 0,
    };
  },

  toJSON(message: Vehicle): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.brand !== "") {
      obj.brand = message.brand;
    }
    if (message.type !== 0) {
      obj.type = vehicleTypeToJSON(message.type);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Vehicle>, I>>(base?: I): Vehicle {
    return Vehicle.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Vehicle>, I>>(object: I): Vehicle {
    const message = createBaseVehicle() as any;
    message.id = object.id ?? 0;
    message.name = object.name ?? "";
    message.brand = object.brand ?? "";
    message.type = object.type ?? 0;
    return message;
  },
};

export type VehicleServiceService = typeof VehicleServiceService;
export const VehicleServiceService = {
  findOne: {
    path: "/vehicle.VehicleService/FindOne",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: FindOneVehicleConditions) => Buffer.from(FindOneVehicleConditions.encode(value).finish()),
    requestDeserialize: (value: Buffer) => FindOneVehicleConditions.decode(value),
    responseSerialize: (value: Vehicle) => Buffer.from(Vehicle.encode(value).finish()),
    responseDeserialize: (value: Buffer) => Vehicle.decode(value),
  },
  find: {
    path: "/vehicle.VehicleService/Find",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: FindVehicleConditions) => Buffer.from(FindVehicleConditions.encode(value).finish()),
    requestDeserialize: (value: Buffer) => FindVehicleConditions.decode(value),
    responseSerialize: (value: Vehicles) => Buffer.from(Vehicles.encode(value).finish()),
    responseDeserialize: (value: Buffer) => Vehicles.decode(value),
  },
} as const;

export interface VehicleServiceServer extends UntypedServiceImplementation {
  findOne: handleUnaryCall<FindOneVehicleConditions, Vehicle>;
  find: handleUnaryCall<FindVehicleConditions, Vehicles>;
}

export interface VehicleServiceClient extends Client {
  findOne(
    request: FindOneVehicleConditions,
    callback: (error: ServiceError | null, response: Vehicle) => void,
  ): ClientUnaryCall;
  findOne(
    request: FindOneVehicleConditions,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: Vehicle) => void,
  ): ClientUnaryCall;
  findOne(
    request: FindOneVehicleConditions,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: Vehicle) => void,
  ): ClientUnaryCall;
  find(
    request: FindVehicleConditions,
    callback: (error: ServiceError | null, response: Vehicles) => void,
  ): ClientUnaryCall;
  find(
    request: FindVehicleConditions,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: Vehicles) => void,
  ): ClientUnaryCall;
  find(
    request: FindVehicleConditions,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: Vehicles) => void,
  ): ClientUnaryCall;
}

export const VehicleServiceClient = makeGenericClientConstructor(
  VehicleServiceService,
  "vehicle.VehicleService",
) as unknown as {
  new (
    address: string,
    credentials: ChannelCredentials,
    options?: Partial<ClientOptions>,
  ): VehicleServiceClient;
  service: typeof VehicleServiceService;
  serviceName: string;
};

export interface DataLoaderOptions {
  cache?: boolean;
}

export interface DataLoaders {
  rpcDataLoaderOptions?: DataLoaderOptions;
  getDataLoader<T>(identifier: string, constructorFn: () => T): T;
}

type Builtin =
  | Date
  | Function
  | Uint8Array
  | string
  | number
  | boolean
  | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  :
    & P
    & { [K in keyof P]: Exact<P[K], I[K]> }
    & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
