// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: profiles.sql

package storage

import (
	"context"
	"database/sql"
	"errors"
	"github.com/eser/acik.io/pkg/api/business/profiles"
)

const createProfile = `-- name: CreateProfile :one
INSERT INTO "profile" (id, slug)
VALUES ($1, $2) RETURNING id, kind, slug, profile_picture_uri, title, description, show_stories, show_projects, created_at, updated_at, deleted_at
`

// CreateProfile
//
//	INSERT INTO "profile" (id, slug)
//	VALUES ($1, $2) RETURNING id, kind, slug, profile_picture_uri, title, description, show_stories, show_projects, created_at, updated_at, deleted_at
func (q *Queries) CreateProfile(ctx context.Context, arg profiles.CreateProfileParams) (*profiles.Profile, error) {
	row := q.db.QueryRowContext(ctx, createProfile, arg.Id, arg.Slug)
	var i profiles.Profile
	err := row.Scan(
		&i.Id,
		&i.Kind,
		&i.Slug,
		&i.ProfilePictureUri,
		&i.Title,
		&i.Description,
		&i.ShowStories,
		&i.ShowProjects,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	if err != nil && errors.Is(err, sql.ErrNoRows) {
		return nil, nil
	}
	return &i, err
}

const deleteProfile = `-- name: DeleteProfile :execrows
UPDATE "profile"
SET deleted_at = NOW()
WHERE id = $1
`

// DeleteProfile
//
//	UPDATE "profile"
//	SET deleted_at = NOW()
//	WHERE id = $1
func (q *Queries) DeleteProfile(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteProfile, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getProfileById = `-- name: GetProfileById :one
SELECT id, kind, slug, profile_picture_uri, title, description, show_stories, show_projects, created_at, updated_at, deleted_at FROM "profile"
WHERE id = $1
LIMIT 1
`

// GetProfileById
//
//	SELECT id, kind, slug, profile_picture_uri, title, description, show_stories, show_projects, created_at, updated_at, deleted_at FROM "profile"
//	WHERE id = $1
//	LIMIT 1
func (q *Queries) GetProfileById(ctx context.Context, id string) (*profiles.Profile, error) {
	row := q.db.QueryRowContext(ctx, getProfileById, id)
	var i profiles.Profile
	err := row.Scan(
		&i.Id,
		&i.Kind,
		&i.Slug,
		&i.ProfilePictureUri,
		&i.Title,
		&i.Description,
		&i.ShowStories,
		&i.ShowProjects,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	if err != nil && errors.Is(err, sql.ErrNoRows) {
		return nil, nil
	}
	return &i, err
}

const getProfileBySlug = `-- name: GetProfileBySlug :one
SELECT id, kind, slug, profile_picture_uri, title, description, show_stories, show_projects, created_at, updated_at, deleted_at FROM "profile"
WHERE slug = $1
LIMIT 1
`

// GetProfileBySlug
//
//	SELECT id, kind, slug, profile_picture_uri, title, description, show_stories, show_projects, created_at, updated_at, deleted_at FROM "profile"
//	WHERE slug = $1
//	LIMIT 1
func (q *Queries) GetProfileBySlug(ctx context.Context, slug string) (*profiles.Profile, error) {
	row := q.db.QueryRowContext(ctx, getProfileBySlug, slug)
	var i profiles.Profile
	err := row.Scan(
		&i.Id,
		&i.Kind,
		&i.Slug,
		&i.ProfilePictureUri,
		&i.Title,
		&i.Description,
		&i.ShowStories,
		&i.ShowProjects,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	if err != nil && errors.Is(err, sql.ErrNoRows) {
		return nil, nil
	}
	return &i, err
}

const listProfiles = `-- name: ListProfiles :many
SELECT id, kind, slug, profile_picture_uri, title, description, show_stories, show_projects, created_at, updated_at, deleted_at FROM "profile"
`

// ListProfiles
//
//	SELECT id, kind, slug, profile_picture_uri, title, description, show_stories, show_projects, created_at, updated_at, deleted_at FROM "profile"
func (q *Queries) ListProfiles(ctx context.Context) ([]*profiles.Profile, error) {
	rows, err := q.db.QueryContext(ctx, listProfiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*profiles.Profile{}
	for rows.Next() {
		var i profiles.Profile
		if err := rows.Scan(
			&i.Id,
			&i.Kind,
			&i.Slug,
			&i.ProfilePictureUri,
			&i.Title,
			&i.Description,
			&i.ShowStories,
			&i.ShowProjects,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProfile = `-- name: UpdateProfile :execrows
UPDATE "profile"
SET slug = $2
WHERE id = $1
`

// UpdateProfile
//
//	UPDATE "profile"
//	SET slug = $2
//	WHERE id = $1
func (q *Queries) UpdateProfile(ctx context.Context, arg profiles.UpdateProfileParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateProfile, arg.Id, arg.Slug)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
