name: production_slim

services:
  api:
    tty: true
    stdin_open: true
    restart: unless-stopped
    build:
      context: ../../
      dockerfile: ./ops/docker/Dockerfile
      target: runner-production
    environment:
      PORT: 8080
      LOG__PRETTY: false
    networks:
      - acik-io-network
    ports:
      - 8080:8080

networks:
  acik-io-network:
    driver: bridge
